---
# L3LS Fabric Values - update these values with caution,
# SOME CHANGES COULD BE DISRUPTIVE.

fabric_name: AVD_FABRIC

# Enable vlan aware bundles
vxlan_vlan_aware_bundles: false

# bgp peer groups passwords
bgp_peer_groups:
  IPv4_UNDERLAY_PEERS:
    password: "AQQvKeimxJu+uGQ/yYvv9w=="
  EVPN_OVERLAY_PEERS:
    password: "q+VNViP5i4rVjW1cxFv2wA=="
  MLAG_IPv4_UNDERLAY_PEER:
    password: "vnEaG8gMeQf3d3cN6PktXQ=="

# Spine Switches
spine:
  defaults:
    platform: vEOS-LAB
    bgp_as: 65001
    loopback_ipv4_pool: 192.168.255.0/24
    bgp_defaults:
      - 'no bgp default ipv4-unicast'
      - 'distance bgp 20 200 200'
      - 'graceful-restart restart-time 300'
      - 'graceful-restart'
    mlag_peer_ipv4_pool: 10.255.252.0/24
    mlag_peer_l3_ipv4_pool: 10.255.251.0/24
  nodes:
    AVD-VEOS1:
      id: 1
      mgmt_ip: 198.18.99.101/24
    AVD-VEOS2:
      id: 2
      mgmt_ip: 198.18.99.102/24

# Leaf switch groups
# A maximum of two nodes can form a leaf group
# When two nodes are in a leaf group this will automatically form mlag pair

l3leaf:
  defaults:
    platform: vEOS-LAB
    loopback_ipv4_pool: 192.168.255.0/24
    loopback_ipv4_offset: 2
    vtep_loopback_ipv4_pool: 192.168.254.0/24
    uplink_interfaces: ['Ethernet1', 'Ethernet2']
    uplink_switches: ['AVD-VEOS1', 'AVD-VEOS2']
    uplink_ipv4_pool: 172.31.255.0/24
    mlag_interfaces: [ Ethernet3, Ethernet4 ]
    mlag_peer_ipv4_pool: 10.255.252.0/24
    mlag_peer_l3_ipv4_pool: 10.255.251.0/24
    virtual_router_mac_address: 00:1c:73:00:dc:01
    bgp_defaults:
      - 'no bgp default ipv4-unicast'
      - 'distance bgp 20 200 200'
      - 'graceful-restart restart-time 300'
      - 'graceful-restart'
    spanning_tree_mode: mstp
    spanning_tree_priority: 16384
  node_groups:
    AVD_POD1:
      bgp_as: 65101
      nodes:
        AVD-VEOS3:
          id: 3
          mgmt_ip: 198.18.99.103/24
          uplink_switch_interfaces: [Ethernet1, Ethernet1]
        AVD-VEOS4:
          id: 4
          mgmt_ip: 198.18.99.104/24
          uplink_switch_interfaces: [Ethernet2, Ethernet2]
    AVD_POD2:
      bgp_as: 65102
      nodes:
        AVD-VEOS5:
          id: 5
          mgmt_ip: 198.18.99.105/24
          uplink_switch_interfaces: [Ethernet3, Ethernet3]
        AVD-VEOS6:
          id: 6
          mgmt_ip: 198.18.99.106/24
          uplink_switch_interfaces: [Ethernet4, Ethernet4]    
    AVD_BORDER_LEAF:
      bgp_as: 65201
      nodes:
        AVD-VEOS7:
          id: 7
          mgmt_ip: 198.18.99.107/24
          uplink_switch_interfaces: [Ethernet5, Ethernet5]
        AVD-VEOS8:
          id: 8
          mgmt_ip: 198.18.99.108/24
          uplink_switch_interfaces: [Ethernet6, Ethernet6]

#### Override for AVD-VEOS Lab Caveats ####

# Disable update wait-for-convergence and update wait-for-install,
# which is not supported in AVD-VEOS-LAB.
# Refer to design guide

# Update p2p mtu 9000 -> 1500
p2p_uplinks_mtu: 1500

# Adjust default bfd values
bfd_multihop:
  interval: 1200
  min_rx: 1200
  multiplier: 3

